[platformio]
src_dir = .

[env:unit_ch552]
platform = https://github.com/UNIT-Electronics-MX/unit_ch55x_docker_sdk.git
board = unit_ch552
upload_protocol = chprog
upload_command = python $PROJECT_DIR/tools/chprog.py $SOURCE
