[platformio]
src_dir = src

[env:unit_ch552]
platform = https://github.com/UNIT-Electronics-MX/unit_ch55x_sdk.git
board = unit_ch552

; Optional overrides:
; board_build.f_cpu = 24000000
; build_flags =
;   -D PIN_LED=P34
; upload_protocol = auto
; upload_protocol = vnproch55x
; upload_protocol = chprog
; board_upload.bootcfg = 3
